export const fredSeries = [
  ["UNRATE", "Unemployment Rate", "Labor", "%", "monthly"],
  ["PAYEMS", "Nonfarm Payrolls", "Labor", "thousands", "monthly"],
  ["ICSA", "Initial Jobless Claims", "Labor", "thousands", "weekly"],
  ["JTSJOL", "Job Openings", "Labor", "thousands", "monthly"],
  ["U6RATE", "Underemployment Rate", "Labor", "%", "monthly"],
  ["CIVPART", "Labor Force Participation Rate", "Labor", "%", "monthly"],
  ["EMRATIO", "Employment-Population Ratio", "Labor", "%", "monthly"],
  ["CES0500000003", "Average Hourly Earnings", "Labor", "$/hour", "monthly"],
  ["AWHAETP", "Average Weekly Hours", "Labor", "hours", "monthly"],
  ["CPIAUCSL", "Consumer Price Index", "Inflation", "index", "monthly"],
  ["CPILFESL", "Core Consumer Price Index", "Inflation", "index", "monthly"],
  ["PCEPI", "PCE Price Index", "Inflation", "index", "monthly"],
  ["PCEPILFE", "Core PCE Price Index", "Inflation", "index", "monthly"],
  ["PPIACO", "Producer Price Index", "Inflation", "index", "monthly"],
  ["T5YIE", "5-Year Breakeven Inflation", "Inflation", "%", "daily"],
  ["T10YIE", "10-Year Breakeven Inflation", "Inflation", "%", "daily"],
  ["GDPC1", "Real Gross Domestic Product", "Growth", "billions", "quarterly"],
  ["PCECC96", "Real Personal Consumption", "Growth", "billions", "quarterly"],
  ["INDPRO", "Industrial Production", "Growth", "index", "monthly"],
  ["RSAFS", "Retail Sales", "Growth", "millions", "monthly"],
  ["CFNAI", "Chicago Fed National Activity Index", "Growth", "index", "monthly"],
  ["DGORDER", "Durable Goods Orders", "Growth", "millions", "monthly"],
  ["NEWORDER", "Manufacturers New Orders", "Growth", "millions", "monthly"],
  ["FEDFUNDS", "Federal Funds Rate", "Rates", "%", "monthly"],
  ["DGS1MO", "1-Month Treasury Yield", "Rates", "%", "daily"],
  ["DGS3MO", "3-Month Treasury Yield", "Rates", "%", "daily"],
  ["DGS6MO", "6-Month Treasury Yield", "Rates", "%", "daily"],
  ["DGS1", "1-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS2", "2-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS5", "5-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS7", "7-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS10", "10-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS20", "20-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS30", "30-Year Treasury Yield", "Rates", "%", "daily"],
  ["T10Y2Y", "10Y–2Y Treasury Spread", "Rates", "percentage points", "daily"],
  ["T10Y3M", "10Y–3M Treasury Spread", "Rates", "percentage points", "daily"],
  ["M2SL", "M2 Money Stock", "Credit", "billions", "monthly"],
  ["NFCI", "National Financial Conditions Index", "Credit", "index", "weekly"],
  ["STLFSI4", "St. Louis Fed Financial Stress Index", "Credit", "index", "weekly"],
  ["VIXCLS", "CBOE Volatility Index", "Credit", "index", "daily"],
  ["BOGMBASE", "Monetary Base", "Credit", "billions", "monthly"],
  ["WALCL", "Federal Reserve Total Assets", "Credit", "millions", "weekly"],
  ["HOUST", "Housing Starts", "Housing", "thousands", "monthly"],
  ["PERMIT", "Building Permits", "Housing", "thousands", "monthly"],
  ["HSN1F", "New One-Family Houses Sold", "Housing", "thousands", "monthly"],
  ["CSUSHPINSA", "Case-Shiller U.S. Home Price Index", "Housing", "index", "monthly"],
  ["MSPUS", "Median New Home Sale Price", "Housing", "$", "quarterly"],
  ["MORTGAGE30US", "30-Year Mortgage Rate", "Housing", "%", "weekly"],
  ["DCOILWTICO", "WTI Crude Oil", "Commodities", "$/barrel", "daily"],
  ["GASREGW", "Regular Gas Price", "Commodities", "$/gallon", "weekly"],
  ["DTWEXBGS", "Trade-Weighted U.S. Dollar", "Markets", "index", "daily"],
  ["DEXUSAL", "Australian Dollar", "Currencies", "USD per AUD", "daily", "identity"],
  ["DEXCAUS", "Canadian Dollar", "Currencies", "USD per CAD", "daily", "invert"],
  ["DEXSZUS", "Swiss Franc", "Currencies", "USD per CHF", "daily", "invert"],
  ["DEXUSEU", "Euro", "Currencies", "USD per EUR", "daily", "identity"],
  ["DEXUSUK", "British Pound", "Currencies", "USD per GBP", "daily", "identity"],
  ["DEXJPUS", "Japanese Yen", "Currencies", "USD per JPY", "daily", "invert"],
  ["DEXUSNZ", "New Zealand Dollar", "Currencies", "USD per NZD", "daily", "identity"],
  ["DEXCHUS", "Chinese Yuan", "Currencies", "USD per CNY", "daily", "invert"],
  ["DEXINUS", "Indian Rupee", "Currencies", "USD per INR", "daily", "invert"],
  ["DEXBZUS", "Brazilian Real", "Currencies", "USD per BRL", "daily", "invert"],
  ["DEXMXUS", "Mexican Peso", "Currencies", "USD per MXN", "daily", "invert"],
  ["DEXSDUS", "Swedish Krona", "Currencies", "USD per SEK", "daily", "invert"],
  ["DEXNOUS", "Norwegian Krone", "Currencies", "USD per NOK", "daily", "invert"],
  ["DEXSIUS", "Singapore Dollar", "Currencies", "USD per SGD", "daily", "invert"],
  ["DEXHKUS", "Hong Kong Dollar", "Currencies", "USD per HKD", "daily", "invert"],
  ["DEXKOUS", "South Korean Won", "Currencies", "USD per KRW", "daily", "invert"],
  ["DEXSFUS", "South African Rand", "Currencies", "USD per ZAR", "daily", "invert"],
  ["USMINE", "Mining and Logging Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USCONS", "Construction Payrolls", "Sector Employment", "thousands", "monthly"],
  ["MANEMP", "Manufacturing Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USINFO", "Information Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USFIRE", "Financial Activities Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USPBS", "Professional Services Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USEHS", "Education and Health Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USLAH", "Leisure and Hospitality Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USGOVT", "Government Payrolls", "Sector Employment", "thousands", "monthly"],
  ["USTRADE", "Trade and Transportation Payrolls", "Sector Employment", "thousands", "monthly"],
];

// Market histories are intentionally fetched only on demand. Committing vendor
// histories to a public repository can conflict with redistribution terms.
export const marketSeries = [];
