export const fredSeries = [
  ["UNRATE", "Unemployment Rate", "Labor", "%", "monthly"],
  ["PAYEMS", "Nonfarm Payrolls", "Labor", "thousands", "monthly"],
  ["ICSA", "Initial Jobless Claims", "Labor", "thousands", "weekly"],
  ["JTSJOL", "Job Openings", "Labor", "thousands", "monthly"],
  ["CPIAUCSL", "Consumer Price Index", "Inflation", "index", "monthly"],
  ["CPILFESL", "Core Consumer Price Index", "Inflation", "index", "monthly"],
  ["PCEPI", "PCE Price Index", "Inflation", "index", "monthly"],
  ["PCEPILFE", "Core PCE Price Index", "Inflation", "index", "monthly"],
  ["GDPC1", "Real Gross Domestic Product", "Growth", "billions", "quarterly"],
  ["INDPRO", "Industrial Production", "Growth", "index", "monthly"],
  ["RSAFS", "Retail Sales", "Growth", "millions", "monthly"],
  ["UMCSENT", "Consumer Sentiment", "Growth", "index", "monthly"],
  ["FEDFUNDS", "Federal Funds Rate", "Rates", "%", "monthly"],
  ["DGS2", "2-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS10", "10-Year Treasury Yield", "Rates", "%", "daily"],
  ["T10Y2Y", "10Y–2Y Treasury Spread", "Rates", "percentage points", "daily"],
  ["BAMLH0A0HYM2", "High-Yield Credit Spread", "Credit", "percentage points", "daily"],
  ["M2SL", "M2 Money Stock", "Credit", "billions", "monthly"],
  ["HOUST", "Housing Starts", "Housing", "thousands", "monthly"],
  ["CSUSHPINSA", "U.S. Home Price Index", "Housing", "index", "monthly"],
  ["DCOILWTICO", "WTI Crude Oil", "Commodities", "$/barrel", "daily"],
  ["GASREGW", "Regular Gas Price", "Commodities", "$/gallon", "weekly"],
  ["VIXCLS", "CBOE Volatility Index", "Markets", "index", "daily"],
  ["DTWEXBGS", "Trade-Weighted U.S. Dollar", "Markets", "index", "daily"],
];

export const marketSeries = [
  ["SPY", "S&P 500 ETF", "Broad Market"],
  ["QQQ", "Nasdaq-100 ETF", "Broad Market"],
  ["IWM", "Russell 2000 ETF", "Broad Market"],
  ["XLK", "Technology Sector", "Sectors"],
  ["XLF", "Financials Sector", "Sectors"],
  ["XLE", "Energy Sector", "Sectors"],
  ["XLV", "Health Care Sector", "Sectors"],
  ["XLI", "Industrials Sector", "Sectors"],
  ["XLY", "Consumer Discretionary Sector", "Sectors"],
  ["XLP", "Consumer Staples Sector", "Sectors"],
  ["XLU", "Utilities Sector", "Sectors"],
  ["XLB", "Materials Sector", "Sectors"],
  ["XLC", "Communication Services Sector", "Sectors"],
  ["GLD", "Gold ETF", "Cross-Asset"],
  ["TLT", "Long Treasury ETF", "Cross-Asset"],
  ["HYG", "High-Yield Bond ETF", "Cross-Asset"],
];
