export const fredSeries = [
  [
    "TDSP",
    "Household Debt-Service Ratio",
    "Credit",
    "%",
    "quarterly",
    "identity",
    {
      provider: "Board of Governors of the Federal Reserve System",
      methodology:
        "Required household debt payments divided by disposable personal income; seasonally adjusted. Quarterly releases, not daily observations.",
    },
  ],
  [
    "DRCCLACBS",
    "Credit Card Loan Delinquency Rate",
    "Credit",
    "%",
    "quarterly",
    "identity",
    {
      provider: "Board of Governors of the Federal Reserve System",
      methodology:
        "Delinquent credit card loans at all commercial banks, seasonally adjusted. Source rate; changes displayed in basis points.",
    },
  ],
  [
    "DRSFRMACBS",
    "Residential Mortgage Delinquency Rate",
    "Credit",
    "%",
    "quarterly",
    "identity",
    {
      provider: "Board of Governors of the Federal Reserve System",
      methodology:
        "Single-family residential mortgage delinquency rate at domestic offices of all commercial banks, seasonally adjusted.",
    },
  ],
  ["UNRATE", "Unemployment Rate", "Labor", "%", "monthly"],
  ["PAYEMS", "Nonfarm Payrolls", "Labor", "thousands", "monthly"],
  ["ICSA", "Initial Jobless Claims", "Labor", "thousands", "weekly"],
  ["JTSJOL", "Job Openings", "Labor", "thousands", "monthly"],
  ["U6RATE", "Underemployment Rate", "Labor", "%", "monthly"],
  ["CIVPART", "Labor Force Participation Rate", "Labor", "%", "monthly"],
  ["EMRATIO", "Employment-Population Ratio", "Labor", "%", "monthly"],
  ["CES0500000003", "Average Hourly Earnings", "Labor", "$/hour", "monthly"],
  ["AWHAETP", "Average Weekly Hours", "Labor", "hours", "monthly"],
  ["CPIAUCSL", "Consumer Price Index", "Inflation", "index", "monthly"],
  ["CPILFESL", "Core Consumer Price Index", "Inflation", "index", "monthly"],
  ["PCEPI", "PCE Price Index", "Inflation", "index", "monthly"],
  ["PCEPILFE", "Core PCE Price Index", "Inflation", "index", "monthly"],
  ["PPIACO", "Producer Price Index", "Inflation", "index", "monthly"],
  ["T5YIE", "5-Year Breakeven Inflation", "Inflation", "%", "daily"],
  ["T10YIE", "10-Year Breakeven Inflation", "Inflation", "%", "daily"],
  ["GDPC1", "Real Gross Domestic Product", "Growth", "billions", "quarterly"],
  ["PCECC96", "Real Personal Consumption", "Growth", "billions", "quarterly"],
  ["INDPRO", "Industrial Production", "Growth", "index", "monthly"],
  ["RSAFS", "Retail Sales", "Growth", "millions", "monthly"],
  [
    "CFNAI",
    "Chicago Fed National Activity Index",
    "Growth",
    "index",
    "monthly",
  ],
  ["DGORDER", "Durable Goods Orders", "Growth", "millions", "monthly"],
  ["NEWORDER", "Manufacturers New Orders", "Growth", "millions", "monthly"],
  ["FEDFUNDS", "Federal Funds Rate", "Rates", "%", "monthly"],
  ["DGS1MO", "1-Month Treasury Yield", "Rates", "%", "daily"],
  ["DGS3MO", "3-Month Treasury Yield", "Rates", "%", "daily"],
  ["DGS6MO", "6-Month Treasury Yield", "Rates", "%", "daily"],
  ["DGS1", "1-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS2", "2-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS5", "5-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS7", "7-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS10", "10-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS20", "20-Year Treasury Yield", "Rates", "%", "daily"],
  ["DGS30", "30-Year Treasury Yield", "Rates", "%", "daily"],
  ["T10Y2Y", "10Y–2Y Treasury Spread", "Rates", "percentage points", "daily"],
  ["T10Y3M", "10Y–3M Treasury Spread", "Rates", "percentage points", "daily"],
  ["M2SL", "M2 Money Stock", "Credit", "billions", "monthly"],
  ["NFCI", "National Financial Conditions Index", "Credit", "index", "weekly"],
  [
    "STLFSI4",
    "St. Louis Fed Financial Stress Index",
    "Credit",
    "index",
    "weekly",
  ],
  ["VIXCLS", "CBOE Volatility Index", "Credit", "index", "daily"],
  ["BOGMBASE", "Monetary Base", "Credit", "billions", "monthly"],
  ["WALCL", "Federal Reserve Total Assets", "Credit", "millions", "weekly"],
  ["HOUST", "Housing Starts", "Housing", "thousands", "monthly"],
  ["PERMIT", "Building Permits", "Housing", "thousands", "monthly"],
  ["HSN1F", "New One-Family Houses Sold", "Housing", "thousands", "monthly"],
  [
    "CSUSHPINSA",
    "Case-Shiller U.S. Home Price Index",
    "Housing",
    "index",
    "monthly",
  ],
  ["MSPUS", "Median New Home Sale Price", "Housing", "$", "quarterly"],
  ["MORTGAGE30US", "30-Year Mortgage Rate", "Housing", "%", "weekly"],
  ["DCOILWTICO", "WTI Crude Oil", "Commodities", "$/barrel", "daily"],
  ["GASREGW", "Regular Gas Price", "Commodities", "$/gallon", "weekly"],
  ["DTWEXBGS", "Trade-Weighted U.S. Dollar", "Markets", "index", "daily"],
  [
    "DEXUSAL",
    "Australian Dollar",
    "Currencies",
    "USD per AUD",
    "daily",
    "identity",
  ],
  [
    "DEXCAUS",
    "Canadian Dollar",
    "Currencies",
    "USD per CAD",
    "daily",
    "invert",
  ],
  ["DEXSZUS", "Swiss Franc", "Currencies", "USD per CHF", "daily", "invert"],
  ["DEXUSEU", "Euro", "Currencies", "USD per EUR", "daily", "identity"],
  [
    "DEXUSUK",
    "British Pound",
    "Currencies",
    "USD per GBP",
    "daily",
    "identity",
  ],
  ["DEXJPUS", "Japanese Yen", "Currencies", "USD per JPY", "daily", "invert"],
  [
    "DEXUSNZ",
    "New Zealand Dollar",
    "Currencies",
    "USD per NZD",
    "daily",
    "identity",
  ],
  ["DEXCHUS", "Chinese Yuan", "Currencies", "USD per CNY", "daily", "invert"],
  ["DEXINUS", "Indian Rupee", "Currencies", "USD per INR", "daily", "invert"],
  ["DEXBZUS", "Brazilian Real", "Currencies", "USD per BRL", "daily", "invert"],
  ["DEXMXUS", "Mexican Peso", "Currencies", "USD per MXN", "daily", "invert"],
  ["DEXSDUS", "Swedish Krona", "Currencies", "USD per SEK", "daily", "invert"],
  [
    "DEXNOUS",
    "Norwegian Krone",
    "Currencies",
    "USD per NOK",
    "daily",
    "invert",
  ],
  [
    "DEXSIUS",
    "Singapore Dollar",
    "Currencies",
    "USD per SGD",
    "daily",
    "invert",
  ],
  [
    "DEXHKUS",
    "Hong Kong Dollar",
    "Currencies",
    "USD per HKD",
    "daily",
    "invert",
  ],
  [
    "DEXKOUS",
    "South Korean Won",
    "Currencies",
    "USD per KRW",
    "daily",
    "invert",
  ],
  [
    "DEXSFUS",
    "South African Rand",
    "Currencies",
    "USD per ZAR",
    "daily",
    "invert",
  ],
  [
    "USMINE",
    "Mining and Logging Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USCONS",
    "Construction Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "MANEMP",
    "Manufacturing Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USINFO",
    "Information Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USFIRE",
    "Financial Activities Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USPBS",
    "Professional Services Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USEHS",
    "Education and Health Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USLAH",
    "Leisure and Hospitality Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USGOVT",
    "Government Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],
  [
    "USTRADE",
    "Trade and Transportation Payrolls",
    "Sector Employment",
    "thousands",
    "monthly",
  ],

  // International CPI replacements are pinned to current FRED successor
  // feeds rather than the archived 2023/2021 OECD export. Eurostat HICPs
  // provide current monthly indexes for the EU members; where FRED's OECD
  // feed is still lagged, the World Bank's latest observed annual inflation
  // rate is used and explicitly labelled in metadata (not an IMF forecast).
  [
    "FPCPITOTLZGCAN",
    "Annual consumer inflation · Canada",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
    },
  ],
  [
    "CP0000DEM086NEST",
    "Harmonized Consumer Price Index · Germany",
    "International Inflation",
    "index",
    "monthly",
    "identity",
    {
      semantic: "index",
      changeType: "percent",
      sourceFamily: "Eurostat HICP",
      successorOf: "DEUCPALTT01IXNBM",
      lastVerifiedObservation: "2026-08-01",
      rightsNote:
        "Eurostat data are copyrighted; cite FRED/Eurostat and follow the source terms.",
    },
  ],
  [
    "CP0000FRM086NEST",
    "Harmonized Consumer Price Index · France",
    "International Inflation",
    "index",
    "monthly",
    "identity",
    {
      semantic: "index",
      changeType: "percent",
      sourceFamily: "Eurostat HICP",
      successorOf: "FRACPALTT01IXNBM",
      lastVerifiedObservation: "2026-08-01",
      rightsNote:
        "Eurostat data are copyrighted; cite FRED/Eurostat and follow the source terms.",
    },
  ],
  [
    "CP0000ITM086NEST",
    "Harmonized Consumer Price Index · Italy",
    "International Inflation",
    "index",
    "monthly",
    "identity",
    {
      semantic: "index",
      changeType: "percent",
      sourceFamily: "Eurostat HICP",
      successorOf: "ITACPALTT01IXNBM",
      lastVerifiedObservation: "2026-08-01",
      rightsNote:
        "Eurostat data are copyrighted; cite FRED/Eurostat and follow the source terms.",
    },
  ],
  [
    "FPCPITOTLZGJPN",
    "Inflation, consumer prices · Japan",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      successorOf: "JPNCPALTT01IXNBM",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
      lastVerifiedObservation: "2025-01-01",
    },
  ],
  [
    "FPCPITOTLZGAUS",
    "Inflation, consumer prices · Australia",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      successorOf: "AUSCPALTT01IXNBQ",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
      lastVerifiedObservation: "2025-01-01",
    },
  ],
  [
    "FPCPITOTLZGCHN",
    "Annual consumer inflation · China",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
    },
  ],
  [
    "FPCPITOTLZGIND",
    "Annual consumer inflation · India",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
    },
  ],
  [
    "FPCPITOTLZGBRA",
    "Annual consumer inflation · Brazil",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
    },
  ],
  [
    "FPCPITOTLZGMEX",
    "Inflation, consumer prices · Mexico",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      successorOf: "MEXCPALTT01IXNBM",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
      lastVerifiedObservation: "2025-01-01",
    },
  ],
  [
    "FPCPITOTLZGKOR",
    "Inflation, consumer prices · South Korea",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      successorOf: "KORCPALTT01IXNBM",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
      lastVerifiedObservation: "2025-01-01",
    },
  ],
  [
    "CP0000ESM086NEST",
    "Harmonized Consumer Price Index · Spain",
    "International Inflation",
    "index",
    "monthly",
    "identity",
    {
      semantic: "index",
      changeType: "percent",
      sourceFamily: "Eurostat HICP",
      successorOf: "ESPCPALTT01IXNBM",
      lastVerifiedObservation: "2026-08-01",
      rightsNote:
        "Eurostat data are copyrighted; cite FRED/Eurostat and follow the source terms.",
    },
  ],
  [
    "FPCPITOTLZGGBR",
    "Inflation, consumer prices · United Kingdom",
    "International Inflation",
    "%",
    "annual",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "World Bank World Development Indicators",
      successorOf: "GBRCPALTT01IXNBM",
      availabilityNote:
        "Annual inflation rate, not a monthly CPI index; reference-year date is January 1.",
      lastVerifiedObservation: "2025-01-01",
    },
  ],

  [
    "NGDPRSAXDCCAQ",
    "Real GDP · Canada",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCDEQ",
    "Real GDP · Germany",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCFRQ",
    "Real GDP · France",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCITQ",
    "Real GDP · Italy",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCJPQ",
    "Real GDP · Japan",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCAUQ",
    "Real GDP · Australia",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCBRQ",
    "Real GDP · Brazil",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCMXQ",
    "Real GDP · Mexico",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCKRQ",
    "Real GDP · South Korea",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],
  [
    "NGDPRSAXDCGBQ",
    "Real GDP · United Kingdom",
    "International Growth",
    "millions local currency",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "IMF International Financial Statistics",
    },
  ],

  [
    "LRHUTTTTCAM156S",
    "Harmonized Unemployment Rate · Canada",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTDEM156S",
    "Harmonized Unemployment Rate · Germany",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTFRM156S",
    "Harmonized Unemployment Rate · France",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTITM156S",
    "Harmonized Unemployment Rate · Italy",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTJPM156S",
    "Harmonized Unemployment Rate · Japan",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTAUM156S",
    "Harmonized Unemployment Rate · Australia",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTMXM156S",
    "Harmonized Unemployment Rate · Mexico",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTKRM156S",
    "Harmonized Unemployment Rate · South Korea",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTESM156S",
    "Harmonized Unemployment Rate · Spain",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],
  [
    "LRHUTTTTGBM156S",
    "Harmonized Unemployment Rate · United Kingdom",
    "International Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "OECD Main Economic Indicators",
    },
  ],

  [
    "CLF16OV",
    "Civilian Labor Force Level",
    "Labor",
    "thousands",
    "monthly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "BLS Current Population Survey",
    },
  ],
  [
    "CE16OV",
    "Employment Level",
    "Labor",
    "thousands",
    "monthly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "BLS Current Population Survey",
    },
  ],
  [
    "AHETPI",
    "Average Hourly Earnings · Production and Nonsupervisory",
    "Labor",
    "$/hour",
    "monthly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "BLS Current Employment Statistics",
    },
  ],
  [
    "LES1252881600Q",
    "Median Usual Weekly Real Earnings",
    "Labor",
    "1982–84 CPI dollars/week",
    "quarterly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "BLS Current Population Survey",
    },
  ],
  [
    "JTSQUR",
    "Quits Rate · Total Nonfarm",
    "Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "BLS Job Openings and Labor Turnover Survey",
    },
  ],
  [
    "JTSHIR",
    "Hires Rate · Total Nonfarm",
    "Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "BLS Job Openings and Labor Turnover Survey",
    },
  ],
  [
    "JTSLDL",
    "Layoffs and Discharges · Total Nonfarm",
    "Labor",
    "thousands",
    "monthly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "BLS Job Openings and Labor Turnover Survey",
    },
  ],
  [
    "JTSTSR",
    "Total Separations Rate · Total Nonfarm",
    "Labor",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "BLS Job Openings and Labor Turnover Survey",
    },
  ],

  [
    "HOUST1F",
    "Housing Starts · 1 Unit",
    "Housing",
    "thousands",
    "monthly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "U.S. Census Bureau",
    },
  ],
  [
    "PERMIT1",
    "Building Permits · 1 Unit",
    "Housing",
    "thousands",
    "monthly",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "U.S. Census Bureau",
    },
  ],
  [
    "MEHOINUSA672N",
    "Real Median Household Income",
    "Housing",
    "$",
    "annual",
    "identity",
    {
      semantic: "quantity",
      changeType: "percent",
      sourceFamily: "U.S. Census Bureau",
    },
  ],
  [
    "MORTGAGE15US",
    "15-Year Fixed Mortgage Rate",
    "Housing",
    "%",
    "weekly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "Freddie Mac Primary Mortgage Market Survey",
    },
  ],

  [
    "BAA10Y",
    "Baa Corporate Bond Spread",
    "Credit",
    "percentage points",
    "daily",
    "identity",
    {
      semantic: "spread",
      changeType: "basis-points",
      sourceFamily: "Federal Reserve Board",
      rightsNote:
        "FRED notes that the Moody's component is proprietary and copyrighted; cite FRED and do not redistribute beyond permitted terms.",
    },
  ],
  [
    "AAA10Y",
    "Aaa Corporate Bond Spread",
    "Credit",
    "percentage points",
    "daily",
    "identity",
    {
      semantic: "spread",
      changeType: "basis-points",
      sourceFamily: "Federal Reserve Board",
      rightsNote:
        "FRED notes that the Moody's component is proprietary and copyrighted; cite FRED and do not redistribute beyond permitted terms.",
    },
  ],
  [
    "BAA",
    "Moody's Seasoned Baa Corporate Bond Yield",
    "Credit",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "Moody's Investors Service",
      rightsNote:
        "Moody's data are copyrighted and proprietary; cite FRED and do not redistribute without permission.",
    },
  ],
  [
    "AAA",
    "Moody's Seasoned Aaa Corporate Bond Yield",
    "Credit",
    "%",
    "monthly",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "Moody's Investors Service",
      rightsNote:
        "Moody's data are copyrighted and proprietary; cite FRED and do not redistribute without permission.",
    },
  ],
  [
    "DFF",
    "Daily Effective Federal Funds Rate",
    "Rates",
    "%",
    "daily",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "Federal Reserve Bank of New York",
    },
  ],
  [
    "SOFR",
    "Secured Overnight Financing Rate",
    "Rates",
    "%",
    "daily",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "Federal Reserve Bank of New York",
    },
  ],
  [
    "DFII5",
    "5-Year Treasury Inflation-Indexed Security",
    "Rates",
    "%",
    "daily",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "U.S. Treasury",
    },
  ],
  [
    "DFII10",
    "10-Year Treasury Inflation-Indexed Security",
    "Rates",
    "%",
    "daily",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "U.S. Treasury",
    },
  ],
  [
    "DFII30",
    "30-Year Treasury Inflation-Indexed Security",
    "Rates",
    "%",
    "daily",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "U.S. Treasury",
    },
  ],
  [
    "T5YIFR",
    "5-Year, 5-Year Forward Inflation Expectation",
    "Inflation",
    "%",
    "daily",
    "identity",
    {
      semantic: "rate",
      changeType: "basis-points",
      sourceFamily: "Federal Reserve Bank of St. Louis",
    },
  ],

  [
    "PALLFNFINDEXM",
    "IMF Primary Commodity Price Index · All Commodities",
    "Commodities",
    "index",
    "monthly",
    "identity",
    {
      semantic: "index",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "PPOILUSDM",
    "IMF Primary Commodity Price · Crude Oil",
    "Commodities",
    "$/barrel",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "POILBREUSDM",
    "IMF Primary Commodity Price · Brent Crude",
    "Commodities",
    "$/barrel",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "POILWTIUSDM",
    "IMF Primary Commodity Price · WTI Crude",
    "Commodities",
    "$/barrel",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "PCOPPUSDM",
    "IMF Primary Commodity Price · Copper",
    "Commodities",
    "$/metric ton",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "PWHEAMTUSDM",
    "IMF Primary Commodity Price · Wheat",
    "Commodities",
    "$/metric ton",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "PMAIZMTUSDM",
    "IMF Primary Commodity Price · Corn",
    "Commodities",
    "$/metric ton",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "PSOYBUSDM",
    "IMF Primary Commodity Price · Soybeans",
    "Commodities",
    "$/metric ton",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "PZINCUSDM",
    "IMF Primary Commodity Price · Zinc",
    "Commodities",
    "$/metric ton",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],
  [
    "PNICKUSDM",
    "IMF Primary Commodity Price · Nickel",
    "Commodities",
    "$/metric ton",
    "monthly",
    "identity",
    {
      semantic: "price",
      changeType: "percent",
      sourceFamily: "International Monetary Fund",
    },
  ],

  [
    "DTWEXAFEGS",
    "Trade-Weighted U.S. Dollar · Advanced Foreign Economies",
    "Currencies",
    "index",
    "daily",
    "identity",
    {
      semantic: "index",
      changeType: "percent",
      sourceFamily: "Federal Reserve Board",
    },
  ],
  [
    "DTWEXEMEGS",
    "Trade-Weighted U.S. Dollar · Emerging Market Economies",
    "Currencies",
    "index",
    "daily",
    "identity",
    {
      semantic: "index",
      changeType: "percent",
      sourceFamily: "Federal Reserve Board",
    },
  ],
];

// Market histories are intentionally fetched only on demand. Committing vendor
// histories to a public repository can conflict with redistribution terms.
export const marketSeries = [];
