// Daily Yahoo Finance benchmarks used by the report's market tape.
//
// VT is an investable ETF proxy for the total world equity market. The catalog
// also contains the default market-preset ETFs and country/region indexes;
// index quotes are points, not USD prices. Keep provider and instrument
// metadata explicit so the UI does not imply that an index level is an ETF
// price.
const yahooHistoryUrl = (symbol) =>
  `https://finance.yahoo.com/quote/${encodeURIComponent(symbol)}/history`;

const yahooDefaults = (symbol) => ({
  id: symbol,
  frequency: "daily",
  provider: "Yahoo Finance",
  source: "Yahoo Finance",
  sourceUrl: yahooHistoryUrl(symbol),
});

export const marketSeries = [
  ...[
    ["VTI", "U.S. total-market equities · Vanguard Total Stock Market ETF"],
    ["IWD", "U.S. large-cap value · iShares Russell 1000 Value ETF"],
    ["IWF", "U.S. large-cap growth · iShares Russell 1000 Growth ETF"],
    ["IWN", "U.S. small-cap value · iShares Russell 2000 Value ETF"],
    ["IWO", "U.S. small-cap growth · iShares Russell 2000 Growth ETF"],
    ["XLE", "U.S. energy · Energy Select Sector SPDR Fund"],
    ["XLV", "U.S. health care · Health Care Select Sector SPDR Fund"],
    ["XLU", "U.S. utilities · Utilities Select Sector SPDR Fund"],
    ["XLK", "U.S. technology · Technology Select Sector SPDR Fund"],
  ].map(([id, name]) => ({
    ...yahooDefaults(id),
    name,
    category: "Global Markets",
    marketRole: "proxy_component",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  })),
  {
    ...yahooDefaults("VT"),
    name: "Global equities · Vanguard Total World Stock Index Fund ETF Shares (ETF proxy)",
    category: "Global Markets",
    marketRole: "global_benchmark",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("SPY"),
    name: "U.S. large-cap equities · State Street SPDR S&P 500 ETF Trust",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("QQQ"),
    name: "U.S. technology equities · Invesco QQQ Trust",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("IWM"),
    name: "U.S. small-cap equities · iShares Russell 2000 ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("EFA"),
    name: "Developed ex-U.S. equities · iShares MSCI EAFE ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("EEM"),
    name: "Emerging-market equities · iShares MSCI Emerging Markets ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("VWO"),
    name: "Emerging-market equities · Vanguard FTSE Emerging Markets Index Fund ETF Shares",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("ACWI"),
    name: "Global equities · iShares MSCI ACWI ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "equity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("TLT"),
    name: "U.S. long Treasury bonds · iShares 20+ Year Treasury Bond ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "fixed_income",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("IEF"),
    name: "U.S. intermediate Treasury bonds · iShares 7-10 Year Treasury Bond ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "fixed_income",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("SHY"),
    name: "U.S. short Treasury bonds · iShares 1-3 Year Treasury Bond ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "fixed_income",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("TIP"),
    name: "U.S. inflation-protected bonds · iShares TIPS Bond ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "fixed_income",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("HYG"),
    name: "U.S. high-yield credit · iShares iBoxx $ High Yield Corporate Bond ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "credit",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("LQD"),
    name: "U.S. investment-grade credit · iShares iBoxx $ Investment Grade Corporate Bond ETF",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "credit",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("VNQ"),
    name: "U.S. real estate · Vanguard Real Estate Index Fund ETF Shares",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "real_estate",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("GLD"),
    name: "Gold · SPDR Gold Shares",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "commodity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("DBC"),
    name: "Broad commodities · Invesco DB Commodity Index Tracking Fund",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "commodity",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("UUP"),
    name: "U.S. dollar · Invesco DB US Dollar Index Bullish Fund",
    category: "Global Markets",
    marketRole: "market_preset",
    assetClass: "currency",
    instrumentType: "ETF",
    unit: "USD/share",
    currency: "USD",
  },
  {
    ...yahooDefaults("^GSPC"),
    name: "United States equities · S&P 500",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "United States",
    instrumentType: "Index",
    unit: "index points",
    currency: "USD",
  },
  {
    ...yahooDefaults("^GSPTSE"),
    name: "Canada equities · S&P/TSX Composite Index",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Canada",
    instrumentType: "Index",
    unit: "index points",
    currency: "CAD",
  },
  {
    ...yahooDefaults("^FTSE"),
    name: "United Kingdom equities · FTSE 100",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "United Kingdom",
    instrumentType: "Index",
    unit: "index points",
    currency: "GBP",
  },
  {
    ...yahooDefaults("^GDAXI"),
    name: "Germany equities · DAX Performance Index",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Germany",
    instrumentType: "Index",
    unit: "index points",
    currency: "EUR",
  },
  {
    ...yahooDefaults("^FCHI"),
    name: "France equities · CAC 40",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "France",
    instrumentType: "Index",
    unit: "index points",
    currency: "EUR",
  },
  {
    ...yahooDefaults("^N225"),
    name: "Japan equities · Nikkei 225",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Japan",
    instrumentType: "Index",
    unit: "index points",
    currency: "JPY",
  },
  {
    ...yahooDefaults("^HSI"),
    name: "Hong Kong equities · Hang Seng Index",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Hong Kong",
    instrumentType: "Index",
    unit: "index points",
    currency: "HKD",
  },
  {
    ...yahooDefaults("^AXJO"),
    name: "Australia equities · S&P/ASX 200",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Australia",
    instrumentType: "Index",
    unit: "index points",
    currency: "AUD",
  },
  {
    ...yahooDefaults("^BSESN"),
    name: "India equities · S&P BSE SENSEX",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "India",
    instrumentType: "Index",
    unit: "index points",
    currency: "INR",
  },
  {
    ...yahooDefaults("^BVSP"),
    name: "Brazil equities · IBOVESPA",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Brazil",
    instrumentType: "Index",
    unit: "index points",
    currency: "BRL",
  },
  {
    ...yahooDefaults("^KS11"),
    name: "South Korea equities · KOSPI Composite Index",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "South Korea",
    instrumentType: "Index",
    unit: "index points",
    currency: "KRW",
  },
  {
    ...yahooDefaults("^TWII"),
    name: "Taiwan equities · TSEC Weighted Index",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Taiwan",
    instrumentType: "Index",
    unit: "index points",
    currency: "TWD",
  },
  {
    ...yahooDefaults("^STI"),
    name: "Singapore equities · STI Index",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Singapore",
    instrumentType: "Index",
    unit: "index points",
    currency: "SGD",
  },
  {
    ...yahooDefaults("^STOXX50E"),
    name: "Euro area equities · EURO STOXX 50",
    category: "Global Equity Benchmarks",
    marketRole: "regional_index",
    region: "Euro area",
    instrumentType: "Index",
    unit: "index points",
    currency: "EUR",
  },
  {
    ...yahooDefaults("^MXX"),
    name: "Mexico equities · IPC Mexico",
    category: "Country Equity Indexes",
    marketRole: "country_index",
    country: "Mexico",
    instrumentType: "Index",
    unit: "index points",
    currency: "MXN",
  },
];
