export const presets = [
  {
    id: "historical-macro",
    mode: "macro",
    label: "Historical macro archives",
    description:
      "U.K. prices since 1209, policy since 1694, output since 1700, and prewar U.S. unemployment; explicitly archived, not live",
    series: [
      "CPIUKA",
      "CPIIUKA",
      "BOERUKA",
      "RGDPMPUKA",
      "LTCYUKA",
      "M0892AUSM156SNBR",
    ],
    measure: "level",
    horizon: "max",
  },
  {
    id: "fiscal-productivity",
    mode: "macro",
    label: "Fiscal health & productivity",
    description:
      "Debt, deficits, receipts, productivity, unit labor costs, and long-run output",
    series: [
      "GFDEBTN",
      "GFDEGDQ188S",
      "FYFSD",
      "FYFRGDA188S",
      "FYFSGDA188S",
      "OPHNFB",
      "ULCNFB",
      "COMPNFB",
      "MPU4900013",
      "GDPCA",
      "GNPCA",
      "A191RL1A225NBEA",
    ],
    measure: "level",
  },
  {
    id: "money-credit-history",
    mode: "macro",
    label: "Money & credit history",
    description:
      "Money, reserves, bank credit, consumer credit, mortgage and corporate liabilities; published definition breaks remain visible",
    series: [
      "M1SL",
      "M2SL",
      "TOTRESNS",
      "H8B1001NCBCMG",
      "BUSLOANS",
      "TOTALSL",
      "HCCSDODNS",
      "HHMSDODNS",
      "NCBDBIQ027S",
    ],
    measure: "yoy",
    horizon: "max",
  },
  {
    id: "demography",
    mode: "macro",
    label: "Demography & housing supply",
    description:
      "Population, aging, fertility, life expectancy, homeownership, vacancy and multifamily construction",
    series: [
      "POPTHM",
      "LFWA64TTUSM647S",
      "SPDYNCBRTINUSA",
      "SPDYNTFRTINUSA",
      "SPDYNLE00INUSA",
      "SPPOP65UPTOZSWLD",
      "RHORUSQ156N",
      "RRVRUSQ156N",
      "HOUST5F",
      "EVACANTUSQ176N",
    ],
    measure: "level",
  },
  {
    id: "commodity-index-history",
    mode: "markets",
    label: "Long-run commodity indexes",
    description:
      "World Bank total, energy, non-energy, agriculture, metals, and fertilizer price indexes; monthly averages, not futures returns",
    series: [
      "WB_CMD_INDEX_TOTAL_INDEX",
      "WB_CMD_INDEX_ENERGY",
      "WB_CMD_INDEX_NON_ENERGY",
      "WB_CMD_INDEX_AGRICULTURE",
      "WB_CMD_INDEX_BEVERAGES",
      "WB_CMD_INDEX_FOOD",
      "WB_CMD_INDEX_OILS_AND_MEALS",
      "WB_CMD_INDEX_GRAINS",
      "WB_CMD_INDEX_RAW_MATERIALS",
      "WB_CMD_INDEX_TIMBER",
      "WB_CMD_INDEX_FERTILIZERS",
      "WB_CMD_INDEX_METALS_AND_MINERALS",
      "WB_CMD_INDEX_PRECIOUS_METALS",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "energy-metals-history",
    mode: "markets",
    label: "Long-run energy & metals",
    description:
      "World Bank monthly commodity benchmarks, including gold and silver back to 1960; spot/reference prices, not total returns",
    series: [
      "WB_CMD_INDEX_TOTAL_INDEX",
      "WB_CMD_CRUDE_OIL_AVERAGE",
      "WB_CMD_CRUDE_OIL_BRENT",
      "WB_CMD_CRUDE_OIL_DUBAI",
      "WB_CMD_CRUDE_OIL_WTI",
      "WB_CMD_COAL_AUSTRALIAN",
      "WB_CMD_NATURAL_GAS_US",
      "WB_CMD_NATURAL_GAS_EUROPE",
      "WB_CMD_LIQUEFIED_NATURAL_GAS_JAPAN",
      "WB_CMD_GOLD",
      "WB_CMD_SILVER",
      "WB_CMD_PLATINUM",
      "WB_CMD_COPPER",
      "WB_CMD_ALUMINUM",
      "WB_CMD_LEAD",
      "WB_CMD_TIN",
      "WB_CMD_NICKEL",
      "WB_CMD_ZINC",
      "WB_CMD_IRON_ORE_CFR_SPOT",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "agriculture-history",
    mode: "markets",
    label: "Long-run food & agriculture",
    description:
      "World Bank agricultural roll-up, food, oils, soft commodities, and fertilizers; monthly benchmarks",
    series: [
      "WB_CMD_INDEX_AGRICULTURE",
      "WB_CMD_INDEX_FOOD",
      "WB_CMD_COCOA",
      "WB_CMD_COFFEE_ARABICA",
      "WB_CMD_COFFEE_ROBUSTA",
      "WB_CMD_TEA_AVG_3_AUCTIONS",
      "WB_CMD_MAIZE",
      "WB_CMD_WHEAT_US_HRW",
      "WB_CMD_RICE_THAI_5",
      "WB_CMD_SOYBEANS",
      "WB_CMD_SOYBEAN_OIL",
      "WB_CMD_PALM_OIL",
      "WB_CMD_SUGAR_WORLD",
      "WB_CMD_COTTON_A_INDEX",
      "WB_CMD_BEEF",
      "WB_CMD_CHICKEN",
      "WB_CMD_LAMB",
      "WB_CMD_BANANA_US",
      "WB_CMD_PHOSPHATE_ROCK",
      "WB_CMD_UREA",
      "WB_CMD_POTASSIUM_CHLORIDE",
      "WB_CMD_DAP",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "global-development",
    mode: "macro",
    label: "Long-run global economy",
    description:
      "World Bank world output, per-capita output, population, trade, investment, saving, and urbanization",
    series: [
      "WDI_WLD_GDP",
      "WDI_WLD_GDPPC",
      "WDI_WLD_POP",
      "WDI_WLD_TRADE",
      "WDI_WLD_INVESTMENT",
      "WDI_WLD_SAVINGS",
      "WDI_WLD_URBAN",
    ],
    measure: "level",
    horizon: "max",
  },
  {
    id: "real-output-per-person",
    mode: "macro",
    label: "Real output per person",
    description:
      "World and major economies since 1960; constant 2015 USD, not purchasing-power-parity income",
    series: [
      "WDI_WLD_GDPPC",
      "WDI_USA_GDPPC",
      "WDI_CAN_GDPPC",
      "WDI_GBR_GDPPC",
      "WDI_DEU_GDPPC",
      "WDI_FRA_GDPPC",
      "WDI_ITA_GDPPC",
      "WDI_JPN_GDPPC",
      "WDI_AUS_GDPPC",
      "WDI_CHN_GDPPC",
      "WDI_IND_GDPPC",
      "WDI_BRA_GDPPC",
      "WDI_MEX_GDPPC",
      "WDI_KOR_GDPPC",
    ],
    measure: "yoy",
    horizon: "max",
  },
  {
    id: "research-factors",
    mode: "markets",
    label: "Long-run research factors",
    description:
      "U.S. and emerging-market size, value, profitability, investment, and momentum; non-investable long-short research indexes",
    series: [
      "FF_US_SIZE",
      "FF_US_VALUE",
      "FF_US_PROFITABILITY",
      "FF_US_INVESTMENT",
      "FF_US_MOMENTUM",
      "FF_EM_MARKET",
      "FF_EM_SIZE",
      "FF_EM_VALUE",
      "FF_EM_PROFITABILITY",
      "FF_EM_INVESTMENT",
      "FF_EM_MOMENTUM",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "extended-etfs",
    mode: "markets",
    label: "Extended ETF proxies",
    description:
      "Public research prehistory joined to ETF returns; monthly styles/sectors/emerging markets, annual S&P 500 and gold",
    series: [
      "SPY_SIM",
      "VTI_SIM",
      "IWD_SIM",
      "IWF_SIM",
      "IWN_SIM",
      "IWO_SIM",
      "XLE_SIM",
      "XLV_SIM",
      "XLU_SIM",
      "XLK_SIM",
      "EEM_SIM",
      "GLD_SIM",
    ],
    measure: "indexed",
    horizon: "max",
    logarithmic: true,
  },
  {
    id: "long-valuation",
    mode: "macro",
    label: "Long-run valuation & housing",
    description:
      "Shiller valuation, dividends, earnings, prices and yields since 1871; annual home-price history since 1890",
    series: [
      "SHILLER_CAPE",
      "SHILLER_TR_CAPE",
      "SHILLER_ECY",
      "SHILLER_DIVIDENDS",
      "SHILLER_EARNINGS",
      "SHILLER_CPI",
      "SHILLER_LONG_RATE",
      "SHILLER_HOME_REAL",
      "SHILLER_HOME_NOMINAL",
    ],
    measure: "level",
    horizon: "max",
  },
  {
    id: "household-credit",
    mode: "macro",
    label: "Household credit",
    description:
      "Household debt burden, mortgage and credit-card delinquencies, borrowing rates, and labor conditions",
    series: [
      "TDSP",
      "DRCCLACBS",
      "DRSFRMACBS",
      "MORTGAGE30US",
      "UNRATE",
      "FEDFUNDS",
    ],
    measure: "level",
  },
  {
    id: "macro",
    mode: "macro",
    label: "Macro pulse",
    description:
      "Broad activity plus prices, jobs, growth, policy, housing, and stress",
    series: [
      "CFNAI",
      "CPIAUCSL",
      "PCEPI",
      "UNRATE",
      "PAYEMS",
      "INDPRO",
      "RSAFS",
      "FEDFUNDS",
      "DGS10",
      "HOUST",
      "DTWEXBGS",
      "NFCI",
    ],
    measure: "yoy",
  },
  {
    id: "sectors",
    mode: "markets",
    label: "U.S. sectors",
    description: "S&P 500 roll-up plus every sector ETF",
    symbols: [
      "SPY",
      "XLC",
      "XLY",
      "XLP",
      "XLE",
      "XLF",
      "XLV",
      "XLI",
      "XLK",
      "XLB",
      "XLRE",
      "XLU",
    ],
    measure: "indexed",
  },
  {
    id: "currencies",
    mode: "macro",
    label: "Currencies",
    description:
      "Dollar indexes plus major currencies in consistent USD-per-unit terms",
    series: [
      "DTWEXBGS",
      "DTWEXAFEGS",
      "DTWEXEMEGS",
      "DEXUSAL",
      "DEXCAUS",
      "DEXSZUS",
      "DEXUSEU",
      "DEXUSUK",
      "DEXJPUS",
      "DEXUSNZ",
      "DEXCHUS",
      "DEXINUS",
      "DEXBZUS",
      "DEXMXUS",
      "DEXSDUS",
      "DEXNOUS",
      "DEXSIUS",
      "DEXHKUS",
      "DEXKOUS",
      "DEXSFUS",
    ],
    measure: "indexed",
  },
  {
    id: "commodities",
    mode: "markets",
    label: "Commodities",
    description:
      "Broad commodity roll-up plus energy, metals, agriculture, and livestock",
    symbols: [
      "DBC",
      "CL=F",
      "BZ=F",
      "NG=F",
      "HO=F",
      "RB=F",
      "GC=F",
      "SI=F",
      "HG=F",
      "PL=F",
      "PA=F",
      "ZC=F",
      "ZW=F",
      "ZS=F",
      "KC=F",
      "SB=F",
      "CT=F",
      "CC=F",
      "LE=F",
    ],
    measure: "indexed",
  },
  {
    id: "labor",
    mode: "macro",
    label: "Labor",
    description:
      "Employment, participation, wages, claims, openings, turnover, and sector payrolls",
    series: [
      "PAYEMS",
      "UNRATE",
      "U6RATE",
      "CIVPART",
      "EMRATIO",
      "ICSA",
      "JTSJOL",
      "CES0500000003",
      "AWHAETP",
      "USMINE",
      "USCONS",
      "MANEMP",
      "USTRADE",
      "USINFO",
      "USFIRE",
      "USPBS",
      "USEHS",
      "USLAH",
      "USGOVT",
      "CLF16OV",
      "CE16OV",
      "AHETPI",
      "JTSQUR",
      "LES1252881600Q",
    ],
    measure: "yoy",
  },
  {
    id: "inflation",
    mode: "macro",
    label: "Inflation",
    description: "Headline and core consumer-price gauges",
    series: [
      "CPIAUCSL",
      "CPILFESL",
      "PCEPI",
      "PCEPILFE",
      "PPIACO",
      "T5YIE",
      "T10YIE",
    ],
    measure: "yoy",
  },
  {
    id: "growth",
    mode: "macro",
    label: "Growth",
    description: "Output, consumption, production, and retail demand",
    series: [
      "CFNAI",
      "GDPC1",
      "PCECC96",
      "INDPRO",
      "RSAFS",
      "DGORDER",
      "NEWORDER",
    ],
    measure: "yoy",
  },
  {
    id: "rates",
    mode: "macro",
    label: "Rates & curve",
    description:
      "Policy, funding, nominal and real Treasury yields, and curve slope",
    series: [
      "FEDFUNDS",
      "DFF",
      "SOFR",
      "DGS1MO",
      "DGS3MO",
      "DGS6MO",
      "DGS1",
      "DGS2",
      "DGS5",
      "DGS7",
      "DGS10",
      "DGS20",
      "DGS30",
      "T10Y2Y",
      "T10Y3M",
      "DFII5",
      "DFII10",
      "DFII30",
      "T5YIFR",
    ],
    measure: "level",
    changeMode: "basis-points",
  },
  {
    id: "housing",
    mode: "macro",
    label: "Housing",
    description:
      "Affordability inputs: construction, prices, household income, and mortgage rates",
    series: [
      "HOUST",
      "HOUST1F",
      "PERMIT",
      "PERMIT1",
      "HSN1F",
      "CSUSHPINSA",
      "MSPUS",
      "MEHOINUSA672N",
      "MORTGAGE30US",
      "MORTGAGE15US",
    ],
    measure: "yoy",
  },
  {
    id: "conditions",
    mode: "macro",
    label: "Financial conditions",
    description: "Liquidity, stress, money, and the dollar",
    series: [
      "NFCI",
      "STLFSI4",
      "VIXCLS",
      "M2SL",
      "BOGMBASE",
      "WALCL",
      "DTWEXBGS",
      "FEDFUNDS",
    ],
    symbols: ["HYG", "LQD"],
    measure: "level",
    changeMode: "points",
  },
  {
    id: "international-economies",
    mode: "macro",
    label: "International economies",
    description:
      "Real output and harmonized unemployment across major economies; compare growth and rates, not currency levels",
    series: [
      "GDPC1",
      "NGDPRSAXDCCAQ",
      "NGDPRSAXDCDEQ",
      "NGDPRSAXDCFRQ",
      "NGDPRSAXDCJPQ",
      "NGDPRSAXDCAUQ",
      "NGDPRSAXDCBRQ",
      "NGDPRSAXDCMXQ",
      "NGDPRSAXDCKRQ",
      "NGDPRSAXDCGBQ",
      "UNRATE",
      "LRHUTTTTCAM156S",
      "LRHUTTTTDEM156S",
      "LRHUTTTTGBM156S",
      "LRHUTTTTJPM156S",
      "LRHUTTTTAUM156S",
      "LRHUTTTTKRM156S",
    ],
    measure: "yoy",
  },
  {
    id: "international-inflation",
    mode: "macro",
    label: "U.S. & European inflation",
    description:
      "Current monthly U.S. CPI and European harmonized consumer-price indexes",
    series: [
      "CPIAUCSL",
      "CP0000DEM086NEST",
      "CP0000FRM086NEST",
      "CP0000ITM086NEST",
      "CP0000ESM086NEST",
    ],
    measure: "yoy",
  },
  {
    id: "annual-inflation",
    mode: "macro",
    label: "Global annual inflation",
    description:
      "World Bank annual inflation rates; annual reference years, not live monthly CPI",
    series: [
      "FPCPITOTLZGCAN",
      "FPCPITOTLZGGBR",
      "FPCPITOTLZGJPN",
      "FPCPITOTLZGAUS",
      "FPCPITOTLZGCHN",
      "FPCPITOTLZGIND",
      "FPCPITOTLZGBRA",
      "FPCPITOTLZGMEX",
      "FPCPITOTLZGKOR",
    ],
    horizon: "3650",
  },
  {
    id: "credit",
    mode: "macro",
    label: "Credit & stress",
    description:
      "Aaa/Baa corporate yields and spreads, market stress, and funding conditions",
    series: [
      "NFCI",
      "STLFSI4",
      "VIXCLS",
      "BAA10Y",
      "AAA10Y",
      "BAA",
      "AAA",
      "DFF",
      "SOFR",
      "FEDFUNDS",
      "M2SL",
      "WALCL",
      "DFII10",
      "T5YIFR",
    ],
    measure: "level",
    changeMode: "points",
  },
  {
    id: "commodity-pulse",
    mode: "macro",
    label: "Commodity pulse",
    description:
      "IMF commodity rollups with energy, metals, and agricultural benchmarks",
    series: [
      "PALLFNFINDEXM",
      "PPOILUSDM",
      "POILBREUSDM",
      "POILWTIUSDM",
      "PCOPPUSDM",
      "PWHEAMTUSDM",
      "PMAIZMTUSDM",
      "PSOYBUSDM",
      "PZINCUSDM",
      "PNICKUSDM",
      "DCOILWTICO",
    ],
    measure: "yoy",
  },
  {
    id: "markets",
    mode: "markets",
    label: "Global markets",
    description:
      "Global roll-up plus U.S., international, factors, bonds, credit, and real assets",
    symbols: [
      "VT",
      "SPY",
      "QQQ",
      "IWM",
      "EFA",
      "EEM",
      "VWO",
      "ACWI",
      "TLT",
      "IEF",
      "SHY",
      "TIP",
      "HYG",
      "LQD",
      "VNQ",
      "GLD",
      "DBC",
      "UUP",
    ],
    measure: "indexed",
  },
  {
    id: "long-assets",
    mode: "markets",
    label: "Century asset classes",
    description:
      "Stocks, bills, bonds, credit, real estate, and gold from 1928",
    series: [
      "HIST_SP500_TR",
      "HIST_US_SMALL",
      "HIST_TBILL",
      "HIST_TBOND10",
      "HIST_BAA_CORP",
      "HIST_REAL_ESTATE",
      "HIST_GOLD",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "style-history",
    mode: "markets",
    label: "Size & style since 1926",
    description:
      "Fama–French market, large/small, value/core/growth research portfolios",
    series: [
      "FF_US_MARKET",
      "FF_LARGE_GROWTH",
      "FF_LARGE_CORE",
      "FF_LARGE_VALUE",
      "FF_SMALL_GROWTH",
      "FF_SMALL_CORE",
      "FF_SMALL_VALUE",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "industry-history",
    mode: "markets",
    label: "Industry history since 1926",
    description:
      "Ten U.S. value-weighted Fama–French industry research portfolios",
    series: [
      "FF_INDUSTRY_NONDURABLES",
      "FF_INDUSTRY_DURABLES",
      "FF_INDUSTRY_MANUFACTURING",
      "FF_INDUSTRY_ENERGY",
      "FF_INDUSTRY_HITECH",
      "FF_INDUSTRY_TELECOM",
      "FF_INDUSTRY_SHOPS",
      "FF_INDUSTRY_HEALTH",
      "FF_INDUSTRY_UTILITIES",
      "FF_INDUSTRY_OTHER",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "global-factors",
    mode: "markets",
    label: "Global factor history",
    description:
      "Developed, ex-U.S., European, Japanese, and Asia-Pacific Fama–French market and style factors",
    series: [
      "FF_DEVELOPED_MARKET",
      "FF_DEVELOPED_SMALL",
      "FF_DEVELOPED_VALUE",
      "FF_DEVELOPED_EXUS_MARKET",
      "FF_DEVELOPED_EXUS_SMALL",
      "FF_DEVELOPED_EXUS_VALUE",
      "FF_EUROPE_MARKET",
      "FF_EUROPE_SMALL",
      "FF_EUROPE_VALUE",
      "FF_JAPAN_MARKET",
      "FF_JAPAN_SMALL",
      "FF_JAPAN_VALUE",
      "FF_ASIAPAC_EXJP_MARKET",
      "FF_ASIAPAC_EXJP_SMALL",
      "FF_ASIAPAC_EXJP_VALUE",
    ],
    measure: "indexed",
    horizon: "max",
  },
];

export function presetById(id) {
  return presets.find((preset) => preset.id === id);
}
