export const presets = [
  {
    id: "macro",
    mode: "macro",
    label: "Macro pulse",
    description: "Broad activity plus prices, jobs, growth, policy, housing, and stress",
    series: ["CFNAI", "CPIAUCSL", "PCEPI", "UNRATE", "PAYEMS", "INDPRO", "RSAFS", "FEDFUNDS", "DGS10", "HOUST", "DTWEXBGS", "NFCI"],
    measure: "yoy",
  },
  {
    id: "sectors",
    mode: "markets",
    label: "U.S. sectors",
    description: "S&P 500 roll-up plus every sector ETF",
    symbols: ["SPY", "XLC", "XLY", "XLP", "XLE", "XLF", "XLV", "XLI", "XLK", "XLB", "XLRE", "XLU"],
    measure: "indexed",
  },
  {
    id: "currencies",
    mode: "macro",
    label: "Currencies",
    description: "Dollar indexes plus major currencies in consistent USD-per-unit terms",
    series: ["DTWEXBGS", "DEXUSAL", "DEXCAUS", "DEXSZUS", "DEXUSEU", "DEXUSUK", "DEXJPUS", "DEXUSNZ", "DEXCHUS", "DEXINUS", "DEXBZUS", "DEXMXUS", "DEXSDUS", "DEXNOUS", "DEXSIUS", "DEXHKUS", "DEXKOUS", "DEXSFUS"],
    symbols: ["UUP"],
    measure: "indexed",
  },
  {
    id: "commodities",
    mode: "markets",
    label: "Commodities",
    description: "Broad commodity roll-up plus energy, metals, agriculture, and livestock",
    symbols: ["DBC", "CL=F", "BZ=F", "NG=F", "HO=F", "RB=F", "GC=F", "SI=F", "HG=F", "PL=F", "PA=F", "ZC=F", "ZW=F", "ZS=F", "KC=F", "SB=F", "CT=F", "CC=F", "LE=F"],
    measure: "indexed",
  },
  {
    id: "labor",
    mode: "macro",
    label: "Labor",
    description: "Employment, claims, openings, and sector payrolls",
    series: ["PAYEMS", "UNRATE", "U6RATE", "CIVPART", "EMRATIO", "ICSA", "JTSJOL", "CES0500000003", "AWHAETP", "USMINE", "USCONS", "MANEMP", "USTRADE", "USINFO", "USFIRE", "USPBS", "USEHS", "USLAH", "USGOVT"],
    measure: "yoy",
  },
  {
    id: "inflation",
    mode: "macro",
    label: "Inflation",
    description: "Headline and core consumer-price gauges",
    series: ["CPIAUCSL", "CPILFESL", "PCEPI", "PCEPILFE", "PPIACO", "T5YIE", "T10YIE"],
    measure: "yoy",
  },
  {
    id: "growth",
    mode: "macro",
    label: "Growth",
    description: "Output, consumption, production, and retail demand",
    series: ["CFNAI", "GDPC1", "PCECC96", "INDPRO", "RSAFS", "DGORDER", "NEWORDER"],
    measure: "yoy",
  },
  {
    id: "rates",
    mode: "macro",
    label: "Rates & curve",
    description: "Policy, Treasury yields, and curve slope",
    series: ["FEDFUNDS", "DGS1MO", "DGS3MO", "DGS6MO", "DGS1", "DGS2", "DGS5", "DGS7", "DGS10", "DGS20", "DGS30", "T10Y2Y", "T10Y3M"],
    measure: "level",
    changeMode: "basis-points",
  },
  {
    id: "housing",
    mode: "macro",
    label: "Housing",
    description: "Construction, transactions, prices, and mortgage rates",
    series: ["HOUST", "PERMIT", "HSN1F", "CSUSHPINSA", "MSPUS", "MORTGAGE30US"],
    measure: "yoy",
  },
  {
    id: "conditions",
    mode: "macro",
    label: "Financial conditions",
    description: "Liquidity, stress, money, and the dollar",
    series: ["NFCI", "STLFSI4", "VIXCLS", "M2SL", "BOGMBASE", "WALCL", "DTWEXBGS", "FEDFUNDS"],
    symbols: ["HYG", "LQD"],
    measure: "level",
    changeMode: "points",
  },
  {
    id: "markets",
    mode: "markets",
    label: "Global markets",
    description: "Global roll-up plus U.S., international, factors, bonds, credit, and real assets",
    symbols: ["VT", "SPY", "QQQ", "IWM", "EFA", "EEM", "VWO", "ACWI", "TLT", "IEF", "SHY", "TIP", "HYG", "LQD", "VNQ", "GLD", "DBC", "UUP"],
    measure: "indexed",
  },
  {
    id: "long-assets",
    mode: "markets",
    label: "Century asset classes",
    description: "Stocks, bills, bonds, credit, real estate, and gold from 1928",
    series: ["HIST_SP500_TR", "HIST_US_SMALL", "HIST_TBILL", "HIST_TBOND10", "HIST_BAA_CORP", "HIST_REAL_ESTATE", "HIST_GOLD"],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "style-history",
    mode: "markets",
    label: "Size & style since 1926",
    description: "Fama–French market, large/small, value/core/growth research portfolios",
    series: ["FF_US_MARKET", "FF_LARGE_GROWTH", "FF_LARGE_CORE", "FF_LARGE_VALUE", "FF_SMALL_GROWTH", "FF_SMALL_CORE", "FF_SMALL_VALUE"],
    measure: "indexed",
    horizon: "max",
  },
];

export function presetById(id) {
  return presets.find((preset) => preset.id === id);
}
