export const presets = [
  {
    id: "household-credit",
    mode: "macro",
    label: "Household credit",
    description:
      "Household debt burden, mortgage and credit-card delinquencies, borrowing rates, and labor conditions",
    series: [
      "TDSP",
      "DRCCLACBS",
      "DRSFRMACBS",
      "MORTGAGE30US",
      "UNRATE",
      "FEDFUNDS",
    ],
    measure: "level",
  },
  {
    id: "macro",
    mode: "macro",
    label: "Macro pulse",
    description:
      "Broad activity plus prices, jobs, growth, policy, housing, and stress",
    series: [
      "CFNAI",
      "CPIAUCSL",
      "PCEPI",
      "UNRATE",
      "PAYEMS",
      "INDPRO",
      "RSAFS",
      "FEDFUNDS",
      "DGS10",
      "HOUST",
      "DTWEXBGS",
      "NFCI",
    ],
    measure: "yoy",
  },
  {
    id: "sectors",
    mode: "markets",
    label: "U.S. sectors",
    description: "S&P 500 roll-up plus every sector ETF",
    symbols: [
      "SPY",
      "XLC",
      "XLY",
      "XLP",
      "XLE",
      "XLF",
      "XLV",
      "XLI",
      "XLK",
      "XLB",
      "XLRE",
      "XLU",
    ],
    measure: "indexed",
  },
  {
    id: "currencies",
    mode: "macro",
    label: "Currencies",
    description:
      "Dollar indexes plus major currencies in consistent USD-per-unit terms",
    series: [
      "DTWEXBGS",
      "DTWEXAFEGS",
      "DTWEXEMEGS",
      "DEXUSAL",
      "DEXCAUS",
      "DEXSZUS",
      "DEXUSEU",
      "DEXUSUK",
      "DEXJPUS",
      "DEXUSNZ",
      "DEXCHUS",
      "DEXINUS",
      "DEXBZUS",
      "DEXMXUS",
      "DEXSDUS",
      "DEXNOUS",
      "DEXSIUS",
      "DEXHKUS",
      "DEXKOUS",
      "DEXSFUS",
    ],
    measure: "indexed",
  },
  {
    id: "commodities",
    mode: "markets",
    label: "Commodities",
    description:
      "Broad commodity roll-up plus energy, metals, agriculture, and livestock",
    symbols: [
      "DBC",
      "CL=F",
      "BZ=F",
      "NG=F",
      "HO=F",
      "RB=F",
      "GC=F",
      "SI=F",
      "HG=F",
      "PL=F",
      "PA=F",
      "ZC=F",
      "ZW=F",
      "ZS=F",
      "KC=F",
      "SB=F",
      "CT=F",
      "CC=F",
      "LE=F",
    ],
    measure: "indexed",
  },
  {
    id: "labor",
    mode: "macro",
    label: "Labor",
    description:
      "Employment, participation, wages, claims, openings, turnover, and sector payrolls",
    series: [
      "PAYEMS",
      "UNRATE",
      "U6RATE",
      "CIVPART",
      "EMRATIO",
      "ICSA",
      "JTSJOL",
      "CES0500000003",
      "AWHAETP",
      "USMINE",
      "USCONS",
      "MANEMP",
      "USTRADE",
      "USINFO",
      "USFIRE",
      "USPBS",
      "USEHS",
      "USLAH",
      "USGOVT",
      "CLF16OV",
      "CE16OV",
      "AHETPI",
      "JTSQUR",
      "LES1252881600Q",
    ],
    measure: "yoy",
  },
  {
    id: "inflation",
    mode: "macro",
    label: "Inflation",
    description: "Headline and core consumer-price gauges",
    series: [
      "CPIAUCSL",
      "CPILFESL",
      "PCEPI",
      "PCEPILFE",
      "PPIACO",
      "T5YIE",
      "T10YIE",
    ],
    measure: "yoy",
  },
  {
    id: "growth",
    mode: "macro",
    label: "Growth",
    description: "Output, consumption, production, and retail demand",
    series: [
      "CFNAI",
      "GDPC1",
      "PCECC96",
      "INDPRO",
      "RSAFS",
      "DGORDER",
      "NEWORDER",
    ],
    measure: "yoy",
  },
  {
    id: "rates",
    mode: "macro",
    label: "Rates & curve",
    description:
      "Policy, funding, nominal and real Treasury yields, and curve slope",
    series: [
      "FEDFUNDS",
      "DFF",
      "SOFR",
      "DGS1MO",
      "DGS3MO",
      "DGS6MO",
      "DGS1",
      "DGS2",
      "DGS5",
      "DGS7",
      "DGS10",
      "DGS20",
      "DGS30",
      "T10Y2Y",
      "T10Y3M",
      "DFII5",
      "DFII10",
      "DFII30",
      "T5YIFR",
    ],
    measure: "level",
    changeMode: "basis-points",
  },
  {
    id: "housing",
    mode: "macro",
    label: "Housing",
    description:
      "Affordability inputs: construction, prices, household income, and mortgage rates",
    series: [
      "HOUST",
      "HOUST1F",
      "PERMIT",
      "PERMIT1",
      "HSN1F",
      "CSUSHPINSA",
      "MSPUS",
      "MEHOINUSA672N",
      "MORTGAGE30US",
      "MORTGAGE15US",
    ],
    measure: "yoy",
  },
  {
    id: "conditions",
    mode: "macro",
    label: "Financial conditions",
    description: "Liquidity, stress, money, and the dollar",
    series: [
      "NFCI",
      "STLFSI4",
      "VIXCLS",
      "M2SL",
      "BOGMBASE",
      "WALCL",
      "DTWEXBGS",
      "FEDFUNDS",
    ],
    symbols: ["HYG", "LQD"],
    measure: "level",
    changeMode: "points",
  },
  {
    id: "international-economies",
    mode: "macro",
    label: "International economies",
    description:
      "Real output and harmonized unemployment across major economies; compare growth and rates, not currency levels",
    series: [
      "GDPC1",
      "NGDPRSAXDCCAQ",
      "NGDPRSAXDCDEQ",
      "NGDPRSAXDCFRQ",
      "NGDPRSAXDCJPQ",
      "NGDPRSAXDCAUQ",
      "NGDPRSAXDCBRQ",
      "NGDPRSAXDCMXQ",
      "NGDPRSAXDCKRQ",
      "NGDPRSAXDCGBQ",
      "UNRATE",
      "LRHUTTTTCAM156S",
      "LRHUTTTTDEM156S",
      "LRHUTTTTGBM156S",
      "LRHUTTTTJPM156S",
      "LRHUTTTTAUM156S",
      "LRHUTTTTKRM156S",
    ],
    measure: "yoy",
  },
  {
    id: "international-inflation",
    mode: "macro",
    label: "U.S. & European inflation",
    description:
      "Current monthly U.S. CPI and European harmonized consumer-price indexes",
    series: [
      "CPIAUCSL",
      "CP0000DEM086NEST",
      "CP0000FRM086NEST",
      "CP0000ITM086NEST",
      "CP0000ESM086NEST",
    ],
    measure: "yoy",
  },
  {
    id: "annual-inflation",
    mode: "macro",
    label: "Global annual inflation",
    description:
      "World Bank annual inflation rates; annual reference years, not live monthly CPI",
    series: [
      "FPCPITOTLZGCAN",
      "FPCPITOTLZGGBR",
      "FPCPITOTLZGJPN",
      "FPCPITOTLZGAUS",
      "FPCPITOTLZGCHN",
      "FPCPITOTLZGIND",
      "FPCPITOTLZGBRA",
      "FPCPITOTLZGMEX",
      "FPCPITOTLZGKOR",
    ],
    horizon: "3650",
  },
  {
    id: "credit",
    mode: "macro",
    label: "Credit & stress",
    description:
      "Aaa/Baa corporate yields and spreads, market stress, and funding conditions",
    series: [
      "NFCI",
      "STLFSI4",
      "VIXCLS",
      "BAA10Y",
      "AAA10Y",
      "BAA",
      "AAA",
      "DFF",
      "SOFR",
      "FEDFUNDS",
      "M2SL",
      "WALCL",
      "DFII10",
      "T5YIFR",
    ],
    measure: "level",
    changeMode: "points",
  },
  {
    id: "commodity-pulse",
    mode: "macro",
    label: "Commodity pulse",
    description:
      "IMF commodity rollups with energy, metals, and agricultural benchmarks",
    series: [
      "PALLFNFINDEXM",
      "PPOILUSDM",
      "POILBREUSDM",
      "POILWTIUSDM",
      "PCOPPUSDM",
      "PWHEAMTUSDM",
      "PMAIZMTUSDM",
      "PSOYBUSDM",
      "PZINCUSDM",
      "PNICKUSDM",
      "DCOILWTICO",
    ],
    measure: "yoy",
  },
  {
    id: "markets",
    mode: "markets",
    label: "Global markets",
    description:
      "Global roll-up plus U.S., international, factors, bonds, credit, and real assets",
    symbols: [
      "VT",
      "SPY",
      "QQQ",
      "IWM",
      "EFA",
      "EEM",
      "VWO",
      "ACWI",
      "TLT",
      "IEF",
      "SHY",
      "TIP",
      "HYG",
      "LQD",
      "VNQ",
      "GLD",
      "DBC",
      "UUP",
    ],
    measure: "indexed",
  },
  {
    id: "long-assets",
    mode: "markets",
    label: "Century asset classes",
    description:
      "Stocks, bills, bonds, credit, real estate, and gold from 1928",
    series: [
      "HIST_SP500_TR",
      "HIST_US_SMALL",
      "HIST_TBILL",
      "HIST_TBOND10",
      "HIST_BAA_CORP",
      "HIST_REAL_ESTATE",
      "HIST_GOLD",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "style-history",
    mode: "markets",
    label: "Size & style since 1926",
    description:
      "Fama–French market, large/small, value/core/growth research portfolios",
    series: [
      "FF_US_MARKET",
      "FF_LARGE_GROWTH",
      "FF_LARGE_CORE",
      "FF_LARGE_VALUE",
      "FF_SMALL_GROWTH",
      "FF_SMALL_CORE",
      "FF_SMALL_VALUE",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "industry-history",
    mode: "markets",
    label: "Industry history since 1926",
    description:
      "Ten U.S. value-weighted Fama–French industry research portfolios",
    series: [
      "FF_INDUSTRY_NONDURABLES",
      "FF_INDUSTRY_DURABLES",
      "FF_INDUSTRY_MANUFACTURING",
      "FF_INDUSTRY_ENERGY",
      "FF_INDUSTRY_HITECH",
      "FF_INDUSTRY_TELECOM",
      "FF_INDUSTRY_SHOPS",
      "FF_INDUSTRY_HEALTH",
      "FF_INDUSTRY_UTILITIES",
      "FF_INDUSTRY_OTHER",
    ],
    measure: "indexed",
    horizon: "max",
  },
  {
    id: "global-factors",
    mode: "markets",
    label: "Global factor history",
    description:
      "Developed, ex-U.S., European, Japanese, and Asia-Pacific Fama–French market and style factors",
    series: [
      "FF_DEVELOPED_MARKET",
      "FF_DEVELOPED_SMALL",
      "FF_DEVELOPED_VALUE",
      "FF_DEVELOPED_EXUS_MARKET",
      "FF_DEVELOPED_EXUS_SMALL",
      "FF_DEVELOPED_EXUS_VALUE",
      "FF_EUROPE_MARKET",
      "FF_EUROPE_SMALL",
      "FF_EUROPE_VALUE",
      "FF_JAPAN_MARKET",
      "FF_JAPAN_SMALL",
      "FF_JAPAN_VALUE",
      "FF_ASIAPAC_EXJP_MARKET",
      "FF_ASIAPAC_EXJP_SMALL",
      "FF_ASIAPAC_EXJP_VALUE",
    ],
    measure: "indexed",
    horizon: "max",
  },
];

export function presetById(id) {
  return presets.find((preset) => preset.id === id);
}
